on:
  issues:
    types: [ opened, labeled ]
name: Issue
jobs:
  issueHandler:
    name: Issue Verification
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Verify Issue
      uses: shovel-org/GithubActions@main
      if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
      env:
        GITH_EMAIL: brawl98@outlook.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
